version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: weekly
    rebase-strategy: disabled
    commit-message:
      prefix: "npm"
    ignore:
      - dependency-name: typescript
      - dependency-name: eslint

